//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetPPPIP.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GetPPPIP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; This Script Modified by Devin Blabrough (dblagbro@earthlink.net)
        ///; to be used with Avaya products requireing RAS to connect.
        ///;
        ///;First save this file as &quot;C:WINDOWSsystem32
        ///;asAvaya_ppp_after-dial.scp&quot;
        ///; if &quot;C&quot; is the drive with Windows installed on it.
        ///;
        ///;Then save the username and password in the Window&apos;s dial-up networking
        ///; entry, select the &apos;security&apos; tab in its properties, and select
        ///; the &quot;Show terminal window&quot; and &quot;Run Script&quot; using this script file.
        ///;
        ///;You also must save the username and [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string avaya {
            get {
                return ResourceManager.GetString("avaya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Generic]
        ///Encoding=1
        ///PBVersion=1
        ///Type=1
        ///AutoLogon=0
        ///UseRasCredentials=0
        ///LowDateTime=2055469856
        ///HighDateTime=30295514
        ///DialParamsUID=68964235
        ///Guid=D60D1BD9FFFAC5448AAC8F06664EE1C7
        ///VpnStrategy=0
        ///ExcludedProtocols=0
        ///LcpExtensions=1
        ///DataEncryption=8
        ///SwCompression=1
        ///NegotiateMultilinkAlways=0
        ///SkipDoubleDialDialog=0
        ///DialMode=1
        ///OverridePref=15
        ///RedialAttempts=3
        ///RedialSeconds=60
        ///IdleDisconnectSeconds=1200
        ///RedialOnLinkFailure=0
        ///CallbackMode=0
        ///CustomDialDll=
        ///CustomDialFunc=
        ///CustomRasDialDll=
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string generic_connection {
            get {
                return ResourceManager.GetString("generic_connection", resourceCulture);
            }
        }
    }
}
